### PR TITLE
rearchitect and redesign the site

### PR DESCRIPTION
**Pull request by neverspace**
- Switch from Jekyll to a bespoke build script powered with GitHub Actions
	+ Jekyll did too much magic and was overkill for our website
- Breaking change: syllabi path names change from `/assets/courses` to `/courses`
	+ I am sincerely sorry for your bookmarks :-(
- Re-design
	+ The hacker theme was cool but not cool enough
	+ Support faculty icons :D

How the new site works:
- The `.github/workflows/build_and_deploy.yml` GitHub Action is responsible for building the site and deploying it to GitHub Pages
- The actual build process consists of running a simple Python script in the build/ directory and writing its generated HTML to an index.html file (`python build/build.py > index.html`).
    + This is less complex and more flexible in the ways that matter to us.
    + Hunter students like Python, hopefully this opens up opportunities for contributions :)
- The `index.html` file is published directly to GitHub pages, it's not checked into the repository (so don't go looking for it!)

Future goals:
- Automatically create a prebuild for every pull request that gets created. See #16 for the original discussion about this.
- Swag

### CODE REVIEW

**Comment by neverspace** [comment]
## Old

image

## New 
output

**Comment by neverspace** [comment]
Another problem with the old design was that we weren't actually using the Hacker theme. Rather, I copied a giant CSS file from the Hacker theme repository and modified it a bit to fit our needs. That suckedddddd

**Comment by neverspace** [comment]
Another benefit of this change: it enables local development for the average Joe / Joanne. All you need is a text editor and a Python interpreter, no need to figure out how to install and run Jekyll (I don't have much faith in most Hunter kids having enough resolve to do this). You can easily preview your changes locally just by running `python build/build.py > index.html` and then opening `index.html` in your browser.

**Comment by neverspace** [comment]
I realize this looks like I'm being authoritarian and making such a huge change without consulting anybody. In reality I made most of these changes 6 months ago and asked a number of people and groups of Hunter students for their thoughts way back then. My biggest priority is not forcing something people don't want onto them, so if these changes are unfavorable we can revert.

**Comment by joshnatis** [comment]
It's live! (Also not sure where that revert branch came from but it doesn't matter)

**Pull request merged**
